### ISSUE TITLE
Models with different cases are mapped to the same file

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-workspace#132]
We can define models as `Pet` and `pet`. The runtime can handle that and treat them as different models. But the workspace maps both of them to `pet.json`. As a result, we lost one of two model definitions.

I understand the file mapping is designed to support operating system such as Mac or Windows which has case-insensitive file names by default.

Should we make model names case insensitive too?

**Comment by bajtos** [comment]
I am proposing to implement a validation rule that the model name must me unique case-insensitively within the fact. It is the easiest possible solution to fix the problem and it will not require any extra work in downstream projects like Arc and generator-loopback.
