### ISSUE TITLE
Transactional loading of artifacts

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-workspace#187]
I'd like to start thinking about a new design of workspace that will fix some fundamental issues with 3.0:

**Issues**
- generating ids from keys in the file or file names is not practical since the API supports modifying different entities separately
- renaming is difficult to implement and prone to weird bugs
- sometimes unrelated files are loaded
- overlap in functionality with `loopback-boot`

**Initial 4.0 design**

``` js
// in node
Workspace.load('path/to/workspace', function(err, workspace) {
  // all files are loaded an available for reading / writing their contents
  // in memory

  // renaming a model
  var modelDefinition = workspace.modelDefinitions.findByName('SomeName');
  var modelConfig = workspace.modelConfigs.findByName('SomeName');
  modelDefinition.name = modelConfig.name = 'MyNewName';

  // creating a model
  workspace.modelDefinitions.create('MyNewModel', ...);
  workspace.modelConfigs.create('MyNewModel', ...);

  // NOTE: all of the methods are sync (no callbacks)
  workspace.dataSourceDefinitions.create('MyDataSource', ...);

  // attach a data source
  workspace.modelConfigs.findByName('SomeName').dataSource = 'MyDataSource';

  workspace.save(function(err) {
    // validation errors (err) or
    // contents written to disk
  });
});

// in node / browser
Workspace.observe('file changed', function(file) {
  // notify the user
  // or merge the changes
});

// in a browser / arc (with browserify)
Workspace.load('path/to/workspace', function(err, workspace) {
  // same as above
});
```

`Workspace.load()` should either lock the workspace root or queue subsequent calls to ensure only one callback is modifying a workspace at a time.

@bajtos @seanbrookes thoughts?

**Comment by bajtos** [comment]
The general direction looks good to me.

Nitpick: instead of `workspace.modelDefinitions`, we should probably have `workspace.facets` and then `facet.modelDefinitions`.

**Comment by bajtos** [comment]
> `Workspace.load()` should either lock the workspace root or queue subsequent calls to ensure only one callback is modifying a workspace at a time.

Locking will be IMO difficult to implement, as you have to handle the case where the client does not call unlock, e.g. because the user closes the tab before the request could be sent.

I am proposing to implement an optimistic locking based on version number instead. Each `workspace.load` associates a unique version number with the data. `workspace.save` fails with "conflict error" when the version does not match the version of the last saved data.

Another option may be to employ the offline access & sync algorithm?

**Comment by ritch** [comment]
Just had a discussion with @raymondfeng regarding the new gateway workspace requirements. 

4.0 should be refactored into a new set of modules (or at the minimum separate APIs):

**Packages Metadata API**

Loads node module packages and their contents. Delegates other behavior to the other modules.

**LoopBack Workspace**

Plugs into the package metadata API. Used when loading a package that contains a LoopBack application / the package specifies it should be loaded with this plugin.

**Gateway Workspace**

Plugs into the package metadata API. Used when loading a gateway application / or the package specifies that this plugin should be used to load it.

/cc @raymondfeng
