### ISSUE TITLE
Change the default in the template for normalizeHttpPath

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-workspace#197]
http://docs.strongloop.com/display/LB/config.json#config.json-Remotingproperties

I'd like to change this in the template to `true` and default it to `true` in loopback 3. 

@bajtos do you think this is a breaking change?

**Comment by bajtos** [comment]
I thinks changing the template is not a breaking change, since it affects only newly scaffolded projects. It is a big change though, we should post an update to the mailing list and also notify @dashby3000 et all.

**Comment by mc10** [comment]
I don't think we should change the template until `normalizeHttpPath` is fixed. Currently, it does nothing.

**Comment by bajtos** [comment]
Now that 3.0 is coming soon, I'd like to get this into our roadmap and implement it as a breaking change in strong-remoting, with an easy way how to opt into the old 2.x mode.

Possibly related discussion: #608, especially https://github.com/strongloop/loopback/issues/608#issuecomment-150173804
