### ISSUE TITLE
Please update confluence sites with cors.

### ISSUE THREAD

**Issue by cebor** [strongloop/loopback-workspace#216]
The default `middlware.json` and `config.json` changed the configuration for the cors module a long time ago.

It was very confusing for me to setup `cors` cause the actual documentation does not match the configuration files.

1. [docs/config.json](http://docs.strongloop.com/display/public/LB/config.json)
2. [docs/middlware.json](http://docs.strongloop.com/display/public/LB/middleware.json)

Changing Commit: https://github.com/strongloop/loopback-workspace/commit/61abca0e47839fa9e172a216407b2eb2e51d7621

Can you please update the example configs and also the related configuration option tables. Thanks!

And i also don't get it why `cors` is set to false in `config.json`. Is this right?

**Comment by raymondfeng** [comment]
`cors` used to be handled at remoting level. It is now set to `false` in config.json to skip because the cors middleware takes it over.

**Comment by crandmck** [comment]
I updated those two Confluence articles and moved the CORS information to middleware.json.
