### ISSUE TITLE
Error: getaddrinfo ENOTFOUND blip.strongloop.com

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-workspace#228]
`npm install` in the repo dir encounters this problem:

```
$ npm install
npm WARN deprecated showdown@0.3.1: IMPORTANT hotfix
npm ERR! fetch failed http://blip.strongloop.com/loopback@2.22.0
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND blip.strongloop.com
```
What's up with blip.strongloop.com?

**Comment by crandmck** [comment]
@hacksparrow I cannot reproduce this.  `npm install` works for me. Are you behind a firewall or have a nonstandard DNS setup?

**Comment by hacksparrow** [comment]
@crandmck it is working from my alternate network. I have no idea why the other one is refusing to resolve blip.strongloop.com.
