### ISSUE TITLE
Add DB2 connector to list of data source connectors

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-workspace#243]
@bajtos:
> Can somebody send a PR against loopback-workspace to add the new connector to the list of known & supported connectors?

https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json

The new connector is [loopback-connector-db2](https://github.com/strongloop/loopback-connector-db2).

**Comment by loay** [comment]
https://github.com/strongloop/loopback-workspace/pull/244

**Comment by chandadharap** [comment]
Is this ready to verify? Its been sitting here for many days?

**Comment by crandmck** [comment]
Not sure about verifying, but it's already released in loopback-workspace v. 3.19.0 which is on public npm.  I just confirmed that myself...
```
$ slc loopback:datasource
? Enter the data-source name: foo
? Select the connector for foo: 
  SAP HANA (provided by community) 
  Couchbase (provided by community) 
  IBM DB2 (supported by StrongLoop) 
❯ IBM Cloudant DB (supported by StrongLoop) 
  other 
```

**Comment by cgole** [comment]
@bajtos @0candy @chandadharap  how did this get released before verification? Aren't we missing an important step in the workflow?

**Comment by cgole** [comment]
@chandadharap  @elkorep  is working on verifying this.

**Comment by elkorep** [comment]
Verified that IBM DB2 is on the list for slc loopback:datasource cli command
Same output as @crandmck 

However DB2 is not on the list of connectors on arc yet.

**Comment by crandmck** [comment]
@elkorep Just need to be sure it adds the right stuff to `server/datasources.json`.  I'll assign back to you.  Since the docs are completed, you don't need to reassign it to me.  I presume you can close(?)

**Comment by smartmouse** [comment]
@elkorep I opened an enhancement in arc for the missing connectors, We can move this to done as it shows up in slc loopback:datasource cli command.

**Comment by elkorep** [comment]
The connector is available, I can create a model but these features are not available yet:
- Model discovery.
- Auto-migration and update.

**Comment by cgole** [comment]
We are still verifying this story. Please leave it here. Even if its published, it still needs to be verified.

**Comment by elkorep** [comment]
Connects to database fine and App runs.

Issue with CRUD commands:

I have a db2 database and created the following table:
```
CREATE TABLE CAR 
(Year int, 
Make varchar(255), 
Model varchar(255), 
Colour varchar(255), 
id int NOT NULL);
```

I have a db2 app created in this way:
**slc loopback**
- Created app with defaults called db2app

**slc loopback:datasource**
- Selected IBM DB2 
```
slc loopback:datasource
? Enter the data-source name: mydb2
? Select the connector for mydb2: IBM DB2 (supported by StrongLoop)
```
-  modified server/datasources.json to include the following:
```
"mydb2": {
  "name": "mydb2",
  "connector": "db2",
  "username": <username>,
  "password": <password>,
  "database": <database name>,
  "hostname": <db2 server hostname>,
  "port":     <port number>
}
```
**slc loopback:model***
```
strongbot@zsl12n1:~/elkorep/db2app> slc loopback:model
? Enter the model name: Car
? Select the data-source to attach Car to: mydb2 (db2)
? Select model's base class PersistedModel
? Expose Car via the REST API? Yes
? Custom plural form (used to build REST URL):
? Common model or server only? common
Let's add some Car properties now.

Enter an empty property name when done.
? Property name: Year
(!) generator#invoke() is deprecated. Use generator#composeWith() - see http://yeoman.io/authoring/composability.html
   invoke   loopback:property
? Property type: number
? Required? No

Let's add another Car property.
Enter an empty property name when done.
? Property name: Make
(!) generator#invoke() is deprecated. Use generator#composeWith() - see http://yeoman.io/authoring/composability.html
   invoke   loopback:property
? Property type: string
? Required? No

Let's add another Car property.
Enter an empty property name when done.
? Property name: Model
(!) generator#invoke() is deprecated. Use generator#composeWith() - see http://yeoman.io/authoring/composability.html
   invoke   loopback:property
? Property type: string
? Required? No

Let's add another Car property.
Enter an empty property name when done.
? Property name: Colour
(!) generator#invoke() is deprecated. Use generator#composeWith() - see http://yeoman.io/authoring/composability.html
   invoke   loopback:property
? Property type: string
? Required? No

Let's add another Car property.
Enter an empty property name when done.
? Property name:
```

At this point I ran the app using **slc run**
I go to explorer and try to run a post based on the model:
```
Car {
Year (number, optional),
Make (string, optional),
Model (string, optional),
Colour (string, optional),
id (number, optional)
}
```
But I get the following error
```
Curl
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"Year\": 2013,
  \"Make\": \"Mercedes\",
  \"Model\": \"E350\",
  \"Colour\": \"Black\",
  \"id\": 1
}" "http://zsl12n1:3000/api/Cars"
Request URL
http://zsl12n1:3000/api/Cars
Response Body
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "[IBM][CLI Driver][DB2/AIX64] SQL0206N  \"Year\" is not valid in the context where it is used.  SQLSTATE=42703\n",
    "errors": [],
    "error": "[node-odbc] SQL_ERROR",
    "state": "42S22",
    "stack": "Error: [IBM][CLI Driver][DB2/AIX64] SQL0206N  \"Year\" is not valid in the context where it is used.  SQLSTATE=42703\n\n    at Error (native)"
  }
}
Response Code
500
Response Headers
{
  "date": "Thu, 04 Feb 2016 20:40:28 GMT",
  "x-content-type-options": "nosniff",
  "etag": "W/\"177-iuergQQImcIDuXamaYQzOA\"",
  "x-download-options": "noopen",
  "x-frame-options": "DENY",
  "content-type": "application/json; charset=utf-8",
  "access-control-allow-origin": "http://zsl12n1:3000",
  "access-control-allow-credentials": "true",
  "connection": "keep-alive",
  "vary": "Origin, Accept-Encoding",
  "content-length": "375",
  "x-xss-protection": "1; mode=block"
}
```

**Comment by elkorep** [comment]
@qpresley is merging changes which should fix my  above issues, will verify again once it is merged.

**Comment by chandadharap** [comment]
Once above fix is verified, we can close this. Im not sure arc will be supported for future, we will be migrating arc users to apiconnect.

**Comment by elkorep** [comment]
I opened a seperate bug for this issue https://github.com/strongloop-internal/scrum-loopback/issues/790

**Comment by bajtos** [comment]
@elkorep what's the status of this issue? Can we close it now?

**Comment by cgole** [comment]
This is verified with apiconnect. We have tested this with
