### ISSUE TITLE
Add Cloudant connector to list of data source connectors

### ISSUE THREAD

**Issue by 0candy** [strongloop/loopback-workspace#245]
> Can somebody send a PR against loopback-workspace to add the new connector to the list of known & supported connectors?

https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json

The new connector is [loopback-connector-cloudant](https://github.com/strongloop/loopback-connector-cloudant).

**Comment by smartmouse** [comment]
@0candy what are we supposed to verify?  The loopback-connector-cloudant is in repository and can be installed , should this appear in the arc UI as a default selection?
or on the command line for selection?

**Comment by smartmouse** [comment]
![arc](https://cloud.githubusercontent.com/assets/4519627/12601748/76b4c056-c471-11e5-9645-a2cdc93c65d5.jpg)

does not show up in arc UI

**Comment by smartmouse** [comment]
@bajtos hi this is why I am asking the question in slack. I have no clue what we are supposed to verify and to what extent.

**Comment by 0candy** [comment]
I don't think the change to loopback-workspace has been published yet.

**Comment by chandadharap** [comment]
@0candy This is in verify for a while, who should publish the change to workspace? please link branch here maybe?

**Comment by bajtos** [comment]
Released in `loopback-workspace@3.19.0`

IIRC, the screenshot posted in https://github.com/strongloop/loopback-workspace/issues/245#issuecomment-175344105 is manually designed, it won't be updated just by publishing a new loopback-workspace.

However, `slc loopback:datasource` should pick the new connector.

If there is any drop-down in Arc form for datasource, then this drop down may pick the new connectors too, but I am not sure.

**Comment by 0candy** [comment]
@smartmouse Please verify.

**Comment by cgole** [comment]
@smartmouse steps to verify - https://docs.strongloop.com/display/LB/Cloudant+connector

**Comment by smartmouse** [comment]
yes, slc loopback:datasource, -- will show IBM Cloudant DB (supported by StrongLoop).
but IBM cloudant DB is not showing in arc as  one of the data source nor in the connector

**Comment by 0candy** [comment]
List of connectors are hardcoded in arc:
https://github.com/strongloop/strong-arc/blob/844a34ec764bb31b7af01c6b435ac3ce46897bd9/client/www/scripts/modules/datasource/datasource.services.js#L230

**Comment by smartmouse** [comment]
On the command line:
![image](https://cloud.githubusercontent.com/assets/4519627/12770673/6824b7f6-c9f0-11e5-900f-1aaa3139a209.png)

**Comment by smartmouse** [comment]
![image](https://cloud.githubusercontent.com/assets/4519627/12770805/997dbeb4-c9f1-11e5-9c2f-87873ca096e1.png)

so cannot use with arc .

**Comment by smartmouse** [comment]
if we are just validating if the cloudant-connector is showing up from the command line, it does with slc loopback:datasource.  LGTM  . (Not will not work with arc as connector is not showing up as selection)

**Comment by cgole** [comment]
We are still verifying this story. Please leave it here. Even if its published, it still needs to be verified.

**Comment by smartmouse** [comment]
Issues opened:
https://waffle.io/strongloop-internal/scrum-loopback/cards/56b3c9521d2828320064316e

https://waffle.io/strongloop-internal/scrum-arc/cards/56b21faa7cee739500220afa

**Comment by chandadharap** [comment]
Lets close this since arc may or may not support this. we'll be migrating arc users to api connect.

**Comment by smartmouse** [comment]
yes, we can close this now, we will be verifying this in apic space as well
