### ISSUE TITLE
npm test error on ppcLE for loopback-connector-cloudant

### ISSUE THREAD

**Issue by smartmouse** [strongloop/loopback-workspace#250]
strongbot@plnx131:~/testCloudant> npm install loopback-connector-cloudant
WARN engine follow@0.12.1: wanted: {"node":"0.12.x || 0.10.x || 0.8.x"} (current                                   : {"node":"4.2.6","npm":"2.14.12"})
loopback-connector-cloudant@1.0.4 node_modules/loopback-connector-cloudant
├── async@1.5.2
├── loopback-connector@2.3.0
├── debug@2.2.0 (ms@0.7.1)
├── lodash@3.10.1
└── cloudant@1.4.1 (nano@6.2.0)
strongbot@plnx131:~/testCloudant> cd node_modules/loopback-connector-cloudant/
strongbot@plnx131:~/testCloudant/node_modules/loopback-connector-cloudant> ls
CHANGES          index.js  LICENSE   node_modules  README.md
CONTRIBUTING.md  lib       Makefile  package.json
strongbot@plnx131:~/testCloudant/node_modules/loopback-connector-cloudant> npm i                                   nstall
eslint-config-strongloop@1.0.2 node_modules/eslint-config-strongloop

rc@1.1.6 node_modules/rc
├── ini@1.3.4
├── deep-extend@0.4.1
├── strip-json-comments@1.0.4
└── minimist@1.2.0

should@7.1.1 node_modules/should
├── should-type@0.2.0
├── should-equal@0.5.0
└── should-format@0.3.1

mocha@2.4.5 node_modules/mocha
├── escape-string-regexp@1.0.2
├── commander@2.3.0
├── diff@1.4.0
├── growl@1.8.1
├── supports-color@1.2.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

loopback-datasource-juggler@2.45.0 node_modules/loopback-datasource-juggler
├── inflection@1.8.0
├── depd@1.1.0
├── async@1.0.0
├── node-uuid@1.4.7
├── qs@3.1.0
└── traverse@0.6.6

sinon@1.17.3 node_modules/sinon
├── formatio@1.1.1
├── samsam@1.1.2
├── lolex@1.3.2
└── util@0.10.3 (inherits@2.0.1)

eslint@1.10.3 node_modules/eslint
├── escape-string-regexp@1.0.4
├── path-is-absolute@1.0.0
├── object-assign@4.0.1
├── path-is-inside@1.0.1
├── strip-json-comments@1.0.4
├── globals@8.18.0
├── xml-escape@1.0.0
├── estraverse@4.1.1
├── esutils@2.0.2
├── estraverse-fb@1.3.1
├── text-table@0.2.0
├── espree@2.2.5
├── user-home@2.0.0 (os-homedir@1.0.1)
├── is-resolvable@1.0.0 (tryit@1.0.2)
├── chalk@1.1.1 (ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-                                   ansi@3.0.0)
├── doctrine@0.7.2 (isarray@0.0.1, esutils@1.1.6)
├── glob@5.0.15 (inherits@2.0.1, once@1.3.3, inflight@1.0.4)
├── optionator@0.6.0 (fast-levenshtein@1.0.7, type-check@0.3.2, levn@0.2.5, word                                   wrap@0.0.3, deep-is@0.1.3, prelude-ls@1.1.2)
├── shelljs@0.5.3
├── json-stable-stringify@1.0.1 (jsonify@0.0.0)
├── minimatch@3.0.0 (brace-expansion@1.1.2)
├── lodash.merge@3.3.2 (lodash.istypedarray@3.0.4, lodash.isarguments@3.0.6, lod                                   ash.keysin@3.0.8, lodash._arraycopy@3.0.0, lodash._getnative@3.9.1, lodash._arra                                   yeach@3.0.0, lodash.isarray@3.0.4, lodash.keys@3.1.2, lodash.isplainobject@3.2.0                                   , lodash.toplainobject@3.0.0, lodash._createassigner@3.1.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.5                                   )
├── lodash.clonedeep@3.0.2 (lodash._bindcallback@3.0.1, lodash._baseclone@3.3.0)
├── lodash.omit@3.1.0 (lodash._pickbyarray@3.0.2, lodash._arraymap@3.0.0, lodash                                   ._bindcallback@3.0.1, lodash.restparam@3.6.1, lodash.keysin@3.0.8, lodash._basef                                   latten@3.1.4, lodash._pickbycallback@3.0.0, lodash._basedifference@3.0.3)
├── is-my-json-valid@2.12.4 (jsonpointer@2.0.0, generate-function@2.0.0, xtend@4                                   .0.1, generate-object-property@1.2.0)
├── inquirer@0.11.4 (strip-ansi@3.0.0, ansi-regex@2.0.0, figures@1.4.0, ansi-esc                                   apes@1.1.1, rx-lite@3.1.2, through@2.3.8, cli-width@1.1.1, run-async@0.1.0, cli-                                   cursor@1.0.2, string-width@1.0.1, readline2@1.0.1)
├── file-entry-cache@1.2.4 (flat-cache@1.0.10)
├── handlebars@4.0.5 (source-map@0.4.4, optimist@0.6.1, uglify-js@2.6.1)
├── escope@3.4.0 (esrecurse@3.1.1, es6-weak-map@2.0.1, es6-map@0.1.3)
└── js-yaml@3.4.5 (esprima@2.7.2, argparse@1.0.4)

jscs@2.9.0 node_modules/jscs
├── to-double-quotes@2.0.0
├── to-single-quotes@2.0.0
├── strip-json-comments@1.0.4
├── reserved-words@0.1.1
├── natural-compare@1.2.2
├── estraverse@4.1.1
├── vow@0.4.12
├── pathval@0.1.1
├── jscs-preset-wikimedia@1.0.0
├── esprima@2.7.2
├── exit@0.1.2
├── xmlbuilder@3.1.0
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── strip-bom@2.0.0 (is-utf8@0.2.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.4, supports-color@2.0.0, ansi-styles@2                                   .1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── cli-table@0.3.1 (colors@1.0.3)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.                                   3.3)
├── minimatch@3.0.0 (brace-expansion@1.1.2)
├── resolve@1.1.7
├── vow-fs@0.3.4 (vow-queue@0.4.2, node-uuid@1.4.7, glob@4.5.3)
├── jscs-jsdoc@1.3.1 (jsdoctypeparser@1.2.0, comment-parser@0.3.1)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.1, read@1.0.7, winston@0.8.3,                                    utile@0.2.1)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, r                                   eadable-stream@1.1.13, domutils@1.5.1)
├── jsonlint@1.6.2 (nomnom@1.8.1, JSV@4.0.2)
├── escope@3.4.0 (esrecurse@3.1.1, es6-weak-map@2.0.1, es6-map@0.1.3)
├── js-yaml@3.4.6 (inherit@2.2.3, argparse@1.0.4)
└── babel-jscs@2.0.5 (lodash.assign@3.2.0, babel-core@5.8.35)
strongbot@plnx131:~/testCloudant/node_modules/loopback-connector-cloudant> npm t                                   est

> loopback-connector-cloudant@1.0.4 pretest /home/strongbot/testCloudant/node_mo                                   dules/loopback-connector-cloudant
> eslint ./ && jscs ./

/home/strongbot/testCloudant/node_modules/loopback-connector-cloudant/lib/clouda                                   nt.js
   99:3   error  Unexpected space between function name and paren  no-spaced-fun                                   c
  156:48  error  Unexpected space before function parentheses      space-before-                                   function-paren
  157:23  error  Unexpected space between function name and paren  no-spaced-fun                                   c
  184:5   error  Unexpected space between function name and paren  no-spaced-fun                                   c
  434:46  error  Unexpected space before function parentheses      space-before-                                   function-paren
  454:40  error  Expected error to be handled                      handle-callba                                   ck-err

✖ 6 problems (6 errors, 0 warnings)

npm ERR! Test failed.  See above for more details.

strongbot@plnx131:~/testCloudant/node_modules/loopback-connector-cloudant> node -e "console.log(process.config)"
{ target_defaults:
   { cflags: [],
     default_configuration: 'Release',
     defines: [],
     include_dirs: [],
     libraries: [] },
  variables:
   { asan: 0,
     gas_version: '2.24',
     host_arch: 'ppc64',
     icu_data_file: 'icudt56l.dat',
     icu_data_in: '../../deps/icu/source/data/in/icudt56l.dat',
     icu_endianness: 'l',
     icu_gyp_path: 'tools/icu/icu-generic.gyp',
     icu_locales: 'en,root',
     icu_path: './deps/icu',
     icu_small: true,
     icu_ver_major: '56',
     node_byteorder: 'little',
     node_install_npm: true,
     node_prefix: '/',
     node_release_urlbase: '',
     node_shared_http_parser: false,
     node_shared_libuv: false,
     node_shared_openssl: false,
     node_shared_zlib: false,
     node_tag: '-IBMBuild-4.2.6.0-201601211124',
     node_use_dtrace: false,
     node_use_etw: false,
     node_use_lttng: false,
     node_use_openssl: true,
     node_use_perfctr: false,
     node_use_static_libstdcpp: false,
     openssl_fips: '',
     openssl_no_asm: 0,
     python: '/usr/bin/python',
     target_arch: 'ppc64',
     uv_parent_path: '/deps/uv/',
     uv_use_dtrace: false,
     v8_enable_gdbjit: 0,
     v8_enable_i18n_support: 1,
     v8_no_strict_aliasing: 1,
     v8_optimized_debug: 0,
     v8_parent_path: 'deps/v8',
     v8_random_seed: 0,
     v8_use_snapshot: true,
     want_separate_host_toolset: 0 } }
strongbot@plnx131:~/testCloudant/node_modules/loopback

**Comment by richardpringle** [comment]
@smartmouse, this looks like it's in the wrong-repo. I am going to close.
