### ISSUE TITLE
need a way to validate a workspace dir as a valid app

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/loopback-workspace#258]
- validate path is a valid app (needs method in workspaceService.js in apim-ui, which I think is generated by this loopback-workspace)
  - should lookup name from project.json if valid app and return it in `inspectPath()` call
  - need method to validate path is empty for project initialization flow ( we don't want them to generate a loopback app inside an existing loopback app folder)

**Comment by ritch** [comment]
When you say needs method from @kraman - which module are you referring to?

**Comment by anthonyettinger** [comment]
@ritch Workspace service

**Comment by bajtos** [comment]
Hello, I don't fully understand what is required here. However, we already have a method [Workspace.isValidDir](https://github.com/strongloop/loopback-workspace/blob/master/common/models/workspace.js#L405-L423) that is used in generator-loopback to prevent (re)creating an app in an exiting project ([source](https://github.com/strongloop/generator-loopback/blob/a3a8cb235abdce3ed70de2383f7c4c4ca5e5838b/app/index.js#L153-L162)).

Here is the catch: `Workspace.isValidDir` is not exposed through REST API yet.

@anthonyettinger @kraman @ritch Would this solve this issue for you?

**Comment by bajtos** [comment]
@anthonyettinger @kraman @ritch I am proposing to expose `Workspace.isValidDir` through REST API. Would it be good enough for you? If not, then what else is needed?
