### ISSUE TITLE
Deleting Models

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-workspace#259]
/cc @jtary 

@bajtos when deleting a model.... would you ever want to keep the `ModelConfig` around?

I can't think of any reason that the remove logic should not just go ahead and remove the model config...

Also... it would be nice to add a generator / CLI to remove models. Eg. `loopback:model --remove` or `loopback:remove --model` or similar....

**Comment by bajtos** [comment]
> when deleting a model.... would you ever want to keep the ModelConfig around?
> I can't think of any reason that the remove logic should not just go ahead and remove the model config...

I can imagine one case when I would want to keep the ModelConfig around: moving model definitions from an app project into a shared module for reuse. However, I think that operation would be done manually my moving the relevant source files, not by adding and deleting via `slc`/`apic`.

I am ok with your proposal to delete both model definition and configuration.
