### ISSUE TITLE
Potential race conditions

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-workspace#260]
@anthonyettinger @bajtos @jtary 

We recently ran into an issue in the api designer where loopback-workspace was not able to accept concurrent requests to update model properties without missing writes... I thought we fixed this with the write queue, but apparently it is still an issue.

I'm wondering if we should try and patch this particular issue or continue work on refactoring the workspace API...? Perhaps removing some of the file system or database abstraction would help... It would mean you would need to either take account of the files in generator-loopback and the api designer.

Something like

``` js
function myFunc() {
  var workspace = Workspace.load(dir);
  // make modifications using the workspace API
  var model = workspace.facet('common').createModel('MyModel');
  model.addProperty('MyProperty', ...);
  // then commit the changes to disk
  return workspace.commit();
}
```

This would remove a lot of the magic writing of the cache to disk and make it explicit. It would also allow us to remove some of the other complex code in `connector.js` that makes it impossible to provide a workspace dir..

We could also do this with less drastic changes to the API... Perhaps just adding `init()` and `commit()` or similar.

**Comment by deepakrkris** [comment]
@ritch @raymondfeng , I am not able to reproduce the above issue, after trying multiple times, I have tried 1. adding 300 properties concurrently and 2. loading the workspace 300 times and add a property each time, 3. adding 300 methods concurrently
we should have a joint session this week

**Comment by deepakrkris** [comment]
@kraman thanks for the information. The issue happens only when we try to modify the workspace in 2 separate node processes
