### ISSUE TITLE
Template Naming and Simple Echo Hello World

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-workspace#272]
We should rename the current `hello-world` template to "Notes" and create a new simpler example the demonstrates a very basic hello world.

The new hello-world example should only include

 - a single vanilla Message (eventually a controller + model)
 - a single remote method

**Comment by jannyHou** [comment]
- [ ] **Add new template** 
I think adding a new template is similar to https://github.com/strongloop/loopback-workspace/pull/255

- [ ] **Rename old `hello-world` to `Notes`**

@ritch @bajtos could you explain more about the meaning of `controller` in the following requirement? Thanks:

> a single vanilla Message (eventually a controller + model)

**Comment by bajtos** [comment]
> could you explain more about the meaning of controller in the following requirement? Thanks:

> >    a single vanilla Message (eventually a controller + model)

I think the idea is to use a `Message` model for the initial version (now). When we implement support for controllers, the template should be eventually reworked to use controllers.

@ritch can you confirm please?

/cc @richardpringle

**Comment by richardpringle** [comment]
I have an example controller up which I can adjust according to whatever we decide on. It simply echoes a message right now. I will drop a link in here when I finish with some comments.

**Comment by ritch** [comment]
> @ritch can you confirm please?

exactly

**Comment by jannyHou** [comment]
Pr https://github.com/strongloop/loopback-workspace/pull/278 landed.
Will add controller after feature https://github.com/strongloop/loopback-sandbox/pull/7 landed.

**Comment by ritch** [comment]
We should publish loopback-workspace now... and let @kraman know that a new version is out.

@bajtos ^^^

**Comment by jannyHou** [comment]
Verify Steps:
[1] notes template:

- CRUD operations of model `Note` works fine
- Memory db is created in `datasource.json`
- Model `Note` is attached to db

[2] hello-world template:

- remote method `greet` returns response message
- no db in `datasource.json`
- Model `Message` is attached to db null

**Comment by bajtos** [comment]
> We should publish loopback-workspace now... and let @kraman know that a new version is out.

> @bajtos can you do the publish (unless there is anything that would prevent us from publishing?).

@ritch @jannyHou Since this is a user-facing piece, we need somebody from QA to verify this story first. I am moving it from `#review` to `#verify` and reassigning to @cgole.

**Comment by bajtos** [comment]
@jannyHou you wrote:

> **Verified**
> ready to publish

Who has verified the story?

**Comment by ssh24** [comment]
`Verified`

_**Verification steps**_:

Using **notes** template:
1. Create a loopback app `slc loopback APP_NAME1`
2. Use the `notes` template
3. CRUD operations of model `Note` works fine
4. Memory db is created in `datasource.json`
5. Model `Note` is attached to db

Using **hello-world** template:
1. Create a loopback app `slc loopback APP_NAME2`
2. Use the `hello-world` template
3. remote method greet returns response message
4. no db in `datasource.json`
5. Model `Message` is attached to db null

`Closed`

**Comment by richardpringle** [comment]
@ssh24:
@bajtos can confirm, but I believe the correct process is not to close the issue but to move it to the `TBR` column. 

@jannyHou, you might want to re-open the issue and move it there.

**Comment by bajtos** [comment]
Released as `loopback-workspace@3.29.0`.

**Comment by jannyHou** [comment]
Thanks everyone I am closing it since it's published.
