### ISSUE TITLE
DB2 Connector UI/CLI guide does not include "schema" property.

### ISSUE THREAD

**Issue by Freyert** [strongloop/loopback-workspace#274]
@qpresley I'm not entirely sure if this is necessary, as I haven't used DB2 a lot. However, in my scenario all of my models fall under a particular schema. For instance:

`GOSALES.PRODUCT`

Can I get around setting a schema by naming my model appropriately? Or should we include `schema` [here](https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json#L22-L57).

**Comment by qpresley** [comment]
Schema should likely be included there. You can also pass in a schema as part of the DSN connection string of you use that to connect. When querying tables in DB2 it is always best to fully qualify them with scheme.tablename format

**Comment by richardpringle** [comment]
@qpresley, should @Freyert create a PR to add the `schema` setting to the `db2` workspace model?

**Comment by qpresley** [comment]
@richardpringle yes a PR to pull this in would work fine. <-- @Freyert if you don't mind.

**Comment by bajtos** [comment]
Fixed by #275
