### ISSUE TITLE
Support path param as part of workspace creation

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-workspace#279]
`createFromTemplate` needs to also allow the UI to specify a directory to create the workspace in.

@bajtos @anthonyettinger

**Comment by anthonyettinger** [comment]
something like `POST { name: 'my-app', template: 'hello-world', path: '/Users/aettinger/projects/my-app' }`

**Comment by bajtos** [comment]
@ritch @anthonyettinger at the moment, the directory is controlled by `process.env.WORKSPACE_DIR` or the current working directory. Are you expecting the workspace will switch to the new path after a project was created there? Also loopback-workspace can edit only one project at a time. Is that still okay?

Last but not least, what's the priority of this feature request? Do you have any deadline/milestone that depends on this work?

**Comment by ritch** [comment]
@anthonyettinger has a feature that depends on this.

> Are you expecting the workspace will switch to the new path after a project was created there?

Nope, just create the project in the given directory.
