### ISSUE TITLE
Rework api-server project template into "slc loopback:enable-auth"

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-workspace#280]
Is this template actually that useful? Its removed in `apic` already... maybe we should just get rid of it.

@bajtos @raymondfeng 

*2016-12-08 - update from @bajtos*

I am proposing to create a new generator that would add local auth to _any_ existing loopback project.

```
$ yo loopback
...
  Create a model in your app
    $ yo loopback:model

  Run the app
    $ node .

  Enable local authentication in your app
    $ yo loopback:enable-auth

$ yo loopback:enable-auth
  Modified server/model-config.json
  Added server/boot/authentication.js
```

**Comment by bajtos** [comment]
I don't have a strong opinion whether to keep `api-server` or let it go.

The template configures all models needed for Auth (User, AccessToken, etc.), i.e. api-server = empty-server + local auth. Perhaps we should keep it around but give it a more descriptive name?

**Comment by superkhau** [comment]
I think it's useful for the OOB experience. Unless we got good docs to explain how to set up empty-server + local auth, which IMO we don't.

@ritch Close if you want, hasn't been worked on for half a year.

**Comment by bajtos** [comment]
> Unless we got good docs to explain how to set up empty-server + local auth, which IMO we don't.

I am proposing to create a new generator that would add local auth to _any_ existing loopback project.

```
$ yo loopback
...
  Create a model in your app
    $ yo loopback:model

  Run the app
    $ node .

  Enable local authentication in your app
    $ yo loopback:enable-auth

$ yo loopback:enable-auth
  Modified server/model-config.json
  Added server/boot/authentication.js
```

Should we change the title & the purpose of this user story then?

**Comment by superkhau** [comment]
>I am proposing to create a new generator that would add local auth to any existing loopback project.

I'm good with this. ;) Yes we should change the title/purpose of this story to reflect that IMO.
