### ISSUE TITLE
Cloudant does not support loopback-migrate and discovery

### ISSUE THREAD

**Issue by cgole** [strongloop/loopback-workspace#295]
we need to change https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json#L126-L127 to false

**Comment by bajtos** [comment]
@cgole AFAICT, https://github.com/strongloop/loopback-workspace/pull/296 has been landed, could you please verify, so that we can publish a new version of loopback-workspace?

**Comment by bajtos** [comment]
Ah, nvm, I see that @raymondfeng has already released `loopback-workspace@3.31.0`. I am closing this bug as fixed.
