### ISSUE TITLE
Load isolated Workspaces

### ISSUE THREAD

**Issue by 0candy** [strongloop/loopback-workspace#304]
We should work out a way to load isolated Workspaces. The code that worries me is the global state in process.env.WORKSPACE_DIR. I think we have something working (verified by @anthonyettinger for now), but am worried that this will lead to bugs in the future.

Something like:

var workspaceA = new Workspace(pathToWorkspaceA);
var workspaceB = new Workspace(pathToWorkspaceB);

workspaceA.listProjects(); // => lists projects for this workspace
workspaceB.listProjects(); // => lists projects for this workspace

// this is not possible right now because of `process.env.WORKSPACE_DIR`
The problem is that we cannot do this with the current REST API. It just isn't possible with loopback...

See https://github.com/strongloop/loopback-workspace/pull/303 for background info.

**Comment by raymondfeng** [comment]
To be clear, in the current terms, workspace is the project and it's a singleton. We should make workspace the parent object of facet, which is the container of other artifacts. To support workspace in REST APIs, the url pattern will be become `/api/workspace/:id/...`
