### ISSUE TITLE
CI fails on windows due to POSIX command in pretest

### ISSUE THREAD

**Issue by 0candy** [strongloop/loopback-workspace#322]
The tests are failing on Windows because package.json uses a POSIX shell command (test) that is not supported by Windows.

**Comment by superkhau** [comment]
>Correction, MySQL is set up on these machines. The tests are failing on Windows because package.json uses a POSIX shell command (test) that is not supported by Windows.

Following up from that discussion. We should just check for the env var in the bin/setup-mysql:

```
if (process.env.JENKINS_HOME === '') return; // at the top of the file
```

Should have the same effect as we're doing inline in the NPM script.

**Comment by bajtos** [comment]
Hang on. `bin/setup-mysql` is not for CI only. When a new developer wants to setup their dev environment for running `npm test`, they need to call `bin/setup-mysql` too.

I am ok with moving the env-var check to the script file, as long as we clearly document how to run the script locally when one needs to set up their dev env.

I would also consider using `CI` instead of `JENKINS_HOME`.

**Comment by rmg** [comment]
If the script is relatively non-intrusive and developers don't mind it running every time they do `npm test` then it could be made unconditional.

**Comment by superkhau** [comment]
>do you know why this is necessary in loopback-workspace, why do we need test -z at all

me: ^

>that just makes it so that it only runs on CI

@rmg ^

---

@rmg Do you want to chime in here?

**Comment by superkhau** [comment]
Thanks for chiming in @rmg (forgot to refresh my page so I didn't see your comment earlier).

**Comment by superkhau** [comment]
For historical reference:

>superkhau: do you know why this is necessary in loopback-workspace, why do we need test -z at all
>rmg: that just makes it so that it only runs on CI

---

I think we should just remove the jenkins check altogether.

**Comment by bajtos** [comment]
Let's move the discussion to #311.
