### ISSUE TITLE
discoverModelDefinition does not return on some tables

### ISSUE THREAD

**Issue by eddiemonge** [strongloop/loopback-workspace#331]
if `discoverModelDefinition` includes more than a certain amount of data (enough to cause a JSONified object to be larger than 8192b), then the process hangs.

its sending the data [here](https://github.com/strongloop/loopback-workspace/blob/68af105f184d86a5aeaa205e9b23db65d40939a6/bin/datasource-invoke.js#L87) but not being received [here](https://github.com/strongloop/loopback-workspace/blob/68af105f184d86a5aeaa205e9b23db65d40939a6/common/models/data-source-definition.js#L321).

Anything 8192b and above at that point and this hangs. The number of columns doesn't matter, its the amount of data. Not sure how to fix this since copying the conditions outside of loopback-workspace lets more data go through (up to something like 8mb).

**Comment by bajtos** [comment]
@eddiemonge when copying links to code, please press `y` before copying the URL. When you press `y`, GitHub changes the URL to point to an exact commit, in other words a permalink is created that will work forever. The URLs you used in your comment are pointing to whatever code is currently in the `master` branch. Over time, the code changes and line numbers in the URL will eventually point to a different place.

I have edited the issue description and fixed the links.

**Comment by sam-github** [comment]
@eddiemonge if you want me to look at this, you'll need to provide reproduction instructions. I have no time to read loopback-workspace, and figure out what it is, and how to call it.

**Comment by eddiemonge** [comment]
@bajtos I normally do that. Not sure why I didn't this time. ¯\(°_o)/¯

**Comment by sam-github** [comment]
https://github.ibm.com/eddie/loopback-workspace-test <-- from slack

**Comment by sam-github** [comment]
@eddiemonge loopback-boot@2.23.1 doesn't exist, I'm trying to run with 2.23.0, but do I need to npm link in dev versions of some of the dependencies?

**Comment by eddiemonge** [comment]
`2.23.0` should be fine. `2.23.1` is probably internal only at the moment but not sure why it would be

**Comment by sam-github** [comment]
I get a response back for success and fail for node 4 and node 6 with loopback-workspace-test

**Comment by sam-github** [comment]
I'm looking more closely at the code to see if I can comment on it without a repro.

**Comment by eddiemonge** [comment]
PR posted with Sam's changes and some small tweaks
