### ISSUE TITLE
id shouldn't be there if  "idInjection": false and "forceId": "false"

### ISSUE THREAD

**Issue by rashmihunt** [strongloop/loopback-workspace#486]
When user generates REST APIs and remote models from SOAP datasource using 'lb soap' commands, it generates the model "idInjection": false and "forceId": "false" because 'id' shouldn't be there for the models/API for SOAP discovery. The bug is, even if "idInjection": false and "forceId": "false" when user goes to API explorer(http://0.0.0.0:3000/explorer), 'id' shows up when user tries to test the API

'id' is not really used in SOAP REST API scenario, hence 'id' showing up in API explorer just confusing to the user . See attached 'soaptest.zip' app workspace.. To test, 1) unzip 2) cd to_the_app_dir 3) npm install 4) run 'node .' to invoke explorer 4) Go to the first API, 'id' is there for both input and output which shouldn't be there. 
[soaptest.zip](https://github.com/strongloop/loopback-workspace/files/926412/soaptest.zip)

**Comment by raymondfeng** [comment]
Can you add some code around https://github.com/strongloop/loopback-soap/blob/master/lib/codegen/generator-soap.js#L280? For example:

```js
if (propertyList.id === undefined) {
  propertyList.id = false; // Disable id property
}
models[modelName] = {
    name: modelName,
    properties: propertyList,
    base: 'Model', // Set base model to be Model
  };
```

**Comment by rashmihunt** [comment]
@raymondfeng
https://github.com/strongloop/generator-loopback/blob/master/soap/index.js
```
        forceId: 'false', // in case of soap, we don't need id generated in the model
        idInjection: 'false',
```
is where 'forceId' and 'idInjection' is set to false. Not in above logic you pointed out(I should clean that up as a seperate point). If you see attached zip file, you can see that every model is in-fact generated with 'forceId' and 'idInjection' is set to false.

**Comment by raymondfeng** [comment]
Can you try to change https://github.com/strongloop/generator-loopback/blob/master/soap/index.js#L205 to be `properties: {id: false}`?

**Comment by raymondfeng** [comment]
Per my slack discussion with @rashmihunt, here is our findings:

1. The workspace api is not friendly with `properties: {id: false}`
2. We can introduce a new configuration property for a sub model definition, for example:
```
{
   name: 'SubModel',
   base: 'BaseModel',
   excludeBaseProperties: ['id']
}
```
We can implement the enhancement at https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js#L246.
3. Once 2 is implemented, @rashmihunt can fix the soap model code generation to set up the input/output models to exclude `id`.

**Comment by superkhau** [comment]
- [ ] Add impl in juggler
- [ ] Test case in juggler
- [ ] Doc if any
- [ ] Update generator-loopback to use above impl
- [ ] Test case for generator-loopback

**Comment by rashmihunt** [comment]
PRs: 
-  https://github.com/strongloop/generator-loopback/pull/287 
-  https://github.com/strongloop/loopback-datasource-juggler/pull/1371
