### ISSUE TITLE
Indent size not respected from .editorconfig

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-workspace#489]
_From @devpascoe on April 6, 2017 0:6_

- x Feature request

We have a project that has a .editorconfig file with property indent_size = 4 however when using the CLI generated code reverts to spacing/indenting of 2. Can we set spacing/indenting somewhere?

_Copied from original issue: strongloop/loopback-cli#26_

**Comment by bajtos** [comment]
@devpascoe Hello, thank you for raising this feature request. I agree it would be great to support .editorconfig settings when generating code. Our template files are hard-coded right now, see e.g. [templates/scripts/mode.js.tmpl](https://github.com/strongloop/loopback-workspace/blob/d9431392d4fcbf355a7e8f3765c201df41398e7a/templates/scripts/model.js.tmpl) but more importantly [templates/projects/empty-sever/files/server](https://github.com/strongloop/loopback-workspace/tree/d9431392d4fcbf355a7e8f3765c201df41398e7a/templates/projects/empty-server/files/server). Perhaps we can add a bit of code that will be executed when copying template files and which will update the indentation to match editorconfig settings? Would you like to contribute this improvement yourself?

**Comment by viki53** [comment]
Hi, can this be reopened?

I use tab indentation and every time I generate a file, several things move around, I have to re-indent a bunch of files…

I thought the CLI would help me gain some time, but now I'm not so sure.

**Comment by bajtos** [comment]
@viki53 I am afraid we don't have bandwidth to work on fixing this issue ourselves. Would you like to submit a patch yourself?

**Comment by viki53** [comment]
I can try, yes. Any suggestion about where I might start?

**Comment by bajtos** [comment]
@viki53 
> I can try, yes.

Awesome 🎉 

> Any suggestion about where I might start?

We are using this module to create and modify project files: https://github.com/strongloop/loopback-workspace

The design of loopback-workspace is unfortunately more complex and convoluted that's necessary :( 

This is the code updating JSON file.

https://github.com/strongloop/loopback-workspace/blob/3e80fcd3053199c5de549a5ded5e7773ad2fc5cc/common/models/config-file.js#L104-L115

We are using [fs-extra](https://www.npmjs.com/package/fs-extra) under the hood, these lines may be relevant to our issue:

https://github.com/strongloop/loopback-workspace/blob/3e80fcd3053199c5de549a5ded5e7773ad2fc5cc/common/models/config-file.js#L19-L20

The second part of the problem is how to change indentation in model script template (e.g. `common/models/my-model.js`), here is the relevant code:
https://github.com/strongloop/loopback-workspace/blob/3e80fcd3053199c5de549a5ded5e7773ad2fc5cc/common/models/model-definition.js#L226-L241

Let me know if you need any more help!

**Comment by viki53** [comment]
Thanks!

I started changing some things but I can't really figure out how to test all and where to find the part of the generator (looked into `generator-loopback` but cannot fork it) that asks for the config.

I'd like the generator to ask for the user's preference before creating the default files too (including generating the right `.editorconfig`)…

**Comment by bajtos** [comment]
>  I can't really figure out how to test

I think loopback-workspace tests for model creation are a good place for start. See here: https://github.com/strongloop/loopback-workspace/blob/8726d7ce7662051fe3236c1174d132c8ab038261/test/model-definition.js#L41-L59

> where to find the part of the generator (looked into generator-loopback but cannot fork it) that asks for the config.
> I'd like the generator to ask for the user's preference before creating the default files too (including generating the right .editorconfig)…

See https://github.com/strongloop/generator-loopback/blob/ef092e2262f431b09c2d1987264d47e18159534c/app/index.js, look for actions (named methods) called `askFor{Something}`.
