### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-workspace#519]
The CI for PR https://github.com/strongloop/loopback-workspace/pull/516 failed.  Need to look into it. 
cc @shimks

**Comment by shimks** [comment]
Should have been fixed by https://github.com/strongloop/loopback-sandbox/commit/304cfc10ef6b47ffcc16bb07deb3ab23ae45504e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R18
