### ISSUE TITLE
loopback-workspace 3.x should be able to run on node 8

### ISSUE THREAD

**Issue by horstmannmat** [strongloop/loopback-workspace#535]
Before this [commit](https://github.com/strongloop/loopback-workspace/commit/8fecb33f62a605fd4a314b1a5d8d9d5d89d66bc3#commitcomment-31126470) anybody was able to run with node 8, now it must be between 6 and 8.
The problem is  that npm and yarn, "thinks" that this version is equivalent to the version specified on generator-loopback's [package.json](https://github.com/strongloop/generator-loopback/blob/3.x-latest/package.json), but actually not, since the 3.42.0 version was node 8 compatible.

I looked on the loopback [documentation](https://loopback.io/doc/en/contrib/Long-term-support.html#overview) and loopback 3.x should be able to run on node 8. Loopback-cli depends on this project to run.

| Version    | Status          | Published | EOL                  | Runtime | GA | EOL |
| ---------- | --------------- | --------- | -------------------- |------------------- |------------------- |------------------- |
| LoopBack 4 | Current         | Oct 2018  | Apr 2021 _(minimum)_ | Node 10	 |  Oct 2018 | Apr 2021 |
| Loopback 3 | Active LTS      | Dec 2016  | Dec 2019             | Node 8	 |  Oct 2017 | Dec 2019 |
| Loopback 2 | Maintenance LTS | Jul 2014  | Apr 2019             | Node 6	 |  Oct 2016 | Apr 2019 |

_Originally posted by @horstmannmat in https://github.com/strongloop/loopback-workspace/commit/8fecb33f62a605fd4a314b1a5d8d9d5d89d66bc3#commitcomment-31124589_

**Comment by jannyHou** [comment]
PR merged and released as 3.44.1 @horstmannmat Thank you again for patching it 🎉 !
I am closing this issue, feel free to reopen it if you still have problems.
